from typing_extensions import final
import config
import workers as w
import os
from osgeo import gdal
from workers import server
from qmanager import qProfileManager, Profile
from qhypbrowser import QHypbrowser
from qviewer import qViewer
from PyQt5 import QtWidgets as qtw
from PyQt5 import QtGui as qtg
from PyQt5 import QtCore as qtc
from PyQt5 import QtSql as qts

import sys


class ProgressBar(qtw.QProgressBar):

    def __init__(self, *args, **kwargs):
        super(ProgressBar, self).__init__(*args, **kwargs)
        self.setValue(0)
        self.hide()
        # if self.minimum() != self.maximum():
        #     self.timer = qtc.QTimer(self, timeout=self.onTimeout)
        #     self.timer.start(randint(1, 3) * 1000)
        
    def startDownload(self):
        self.show()
        self.setMaximum(0)
    
    def finishDownload(self):
        self.setMaximum(100)
        self.hide()

class Databaser():
    """" Class for interacting with the database """

    def pull_materials(self):
        ''' returns a list of all materials in the database '''
        query1 = qts.QSqlQuery(self.db)
        # query1.prepare('SELECT * FROM materials')
        # query1.bindValue(':id', material_id)
        query1.exec('SELECT * FROM materials')
        materials = []
        while query1.next():
            materials.append(query1.value(1))
        print(materials)
        return materials
    

    def add_scan(self, id, nickname='None'):
        ''' adds a hyperspectral image to the database '''
        # assume you receive an id like 'EO1H0140312014030110KF'

        presenceCheck = qts.QSqlQuery(self.db)
        presenceCheck.prepare('SELECT * FROM scans WHERE id=:id')
        presenceCheck.bindValue(':id', id)
        presenceCheck.exec_()
        if not presenceCheck.next():
            present = False
            print(f'{id} is not in the database currently')
        else:
            present = True
            print(f'{id} already in database')

        
        def infoSearch(file, term, datalength):
            ''' use this method to pull data from gdal.info '''
            if file.find(term) is not -1:
                i = file.find(term) + len(term)
                data = file[i:i+datalength]
                return data.rstrip()
            else:
                print(f"!!! Did not find '{term}'")
                return None

        def pull_numbers_from_line(file, i, term):
            ''' use this method to pull data from .MET file '''
            line = file[i]
            num = ''
            start = line.find(term) + len(term)

            if start is not -1:
                num = line[start:].rstrip()
                return num
            else:
                print(f"!!! Did not find '{term}'")
                return None

        if not present:

            if os.path.dirname(f'{config.HYPERION_SCANS_PATH}\{id})'):
                filepath = os.path.join(config.HYPERION_SCANS_PATH, id, f'{id}.L1R')
                info = gdal.Info(filepath).split('Corner ')[0]
                print(info)

            metapath = os.path.join(config.HYPERION_SCANS_PATH, id, f'{id}.MET')

            with open(metapath) as f:
                lines = f.read()
                f.seek(0,0)
                linelist = f.readlines()
                # print(lines)
                f.close()


            rows = infoSearch(info, 'Number of Along Track Pixels=', 4)
            samples = infoSearch(info, 'Number of Cross Track Pixels=', 4)
            bands = infoSearch(info, 'Number of Bands=', 3)
            interleave = infoSearch(info, 'Interleave Format=', 3)
            sensor = infoSearch(info, 'L1 File Generated By=', 15)
            datetime = infoSearch(info, 'Time of L1 File Generation=', 20)
            dt = datetime.split(' ')
            try:
                date = dt[0] +' '+ dt[1] + ' ' + dt[3]
                time = dt[2]
            except:
                date = datetime

            c_lat = pull_numbers_from_line(linelist, 1, 'Site Latitude                ')
            c_lon = pull_numbers_from_line(linelist, 2, 'Site Latitude                ')
            ul_lat = pull_numbers_from_line(linelist, 22, ' = ')
            ul_lon = pull_numbers_from_line(linelist, 23, ' = ')
            ur_lon = pull_numbers_from_line(linelist, 24, ' = ')
            ur_lat = pull_numbers_from_line(linelist, 25, ' = ')
            ll_lon = pull_numbers_from_line(linelist, 26, ' = ')
            ll_lat = pull_numbers_from_line(linelist, 27, ' = ')
            lr_lon = pull_numbers_from_line(linelist, 28, ' = ')
            lr_lat = pull_numbers_from_line(linelist, 29, ' = ')

            
            print('\nAdding the following to database...')
            print('id:', id)
            print('nickname:', nickname)
            print('rows:', rows)
            print('samples:', samples)
            print('bands:',bands)
            print('interleave:', interleave)
            print('sensor:', sensor)
            print('date:', date)
            print('time:', time)
            print('c_lat:', c_lat)
            print('c_lon:', c_lon)
            print('ul_lat:', ul_lat)
            print('ul_lon:', ul_lon)
            print('ur_lat:', ur_lat)
            print('ur_lon:', ur_lon)
            print('ll_lat:', ll_lat)
            print('ll_lon:', ll_lon)
            print('lr_lat:', lr_lat)
            print('lr_lon:', lr_lon)
            print('\n')

            insertQuery = qts.QSqlQuery(self.db)
            insertQuery.prepare(
                'INSERT INTO scans(id, nickname, filepath,'
                'rows, samples, bands, sensor, interleave, date, time,'
                'ul_lat, ul_lon, ur_lat, ur_lon, ll_lat, ll_lon, lr_lat,'
                'lr_lon, c_lat, c_lon) VALUES (:id, :nickname, :filepath,'
                ':rows, :samples, :bands, :sensor, :interleave, :date, :time,'
                ':ul_lat, :ul_lon, :ur_lat, :ur_lon, :ll_lat, :ll_lon, :lr_lat,'
                ':lr_lon, :c_lat, :c_lon)'
            )
            insertQuery.bindValue(':id', id)
            insertQuery.bindValue(':nickname', nickname)
            insertQuery.bindValue(':filepath', filepath)
            insertQuery.bindValue(':rows', rows)
            insertQuery.bindValue(':samples', samples)
            insertQuery.bindValue(':bands',bands)
            insertQuery.bindValue(':interleave', interleave)
            insertQuery.bindValue(':sensor', sensor)
            insertQuery.bindValue(':date', date)
            insertQuery.bindValue(':time', time)
            insertQuery.bindValue(':c_lat', c_lat)
            insertQuery.bindValue(':c_lon', c_lon)
            insertQuery.bindValue(':ul_lat', ul_lat)
            insertQuery.bindValue(':ul_lon', ul_lon)
            insertQuery.bindValue(':ur_lat', ur_lat)
            insertQuery.bindValue(':ur_lon', ur_lon)
            insertQuery.bindValue(':ll_lat', ll_lat)
            insertQuery.bindValue(':ll_lon', ll_lon)
            insertQuery.bindValue(':lr_lat', lr_lat)
            insertQuery.bindValue(':lr_lon', lr_lon)
            good = insertQuery.exec_()
            
            if good:
                print(f'scan {id} added successfully to db')
            else:
                print(insertQuery.lastError().text())
                
        


    def __init__(self):
        self.db = qts.QSqlDatabase.addDatabase('QSQLITE')
        self.db.setDatabaseName('data.db')
    
        if not self.db.open():
            error = self.db.lastError().text()
            qtw.QMessageBox.critical(
                None, 'DB Connection Error',
                'Could not open database file: ',
                f'{error}')
            sys.exit(1)
        else:
            print('connected to data.db')

        required_tables = {'materials', 'pixels', 'scans', 'sqlite_sequence'}
        tables = self.db.tables()
        missing_tables = required_tables - set(tables)
        if missing_tables:
            qtw.QMessageBox.critical(
                None, 'DB Integrity Error',
                'Missing tables, please repair DB: '
                f'{missing_tables}')
            sys.exit(1)
        else:
            print('DB integrity check - OK!')



class MyWindow(qtw.QMainWindow):
    """ Class for main application window """

    
    def __init__(self):
        super(MyWindow, self).__init__()
        self.setGeometry(100, 100, 1300, 900) #top, left, width, height
        self.version = '0.1'
        self.setWindowTitle('HyperGix Hyperspectral Software ' + self.version)
        self.databoy = Databaser()

        for dir in os.listdir(config.HYPERION_SCANS_PATH):
            self.databoy.add_scan(dir)

        self.initUI()

        if config.apiKey:
            self.loggedIn = True
        else:
            self.loggedIn = False

        

    def initUI(self):
        self.mainNotebook = MyNotebook(self)
        self.setCentralWidget(self.mainNotebook)

        #Menu Bar
        # self.menubar = self.menuBar()
        # self.file_menu = self.menubar.addMenu('File')


        self.status_bar = qtw.QStatusBar()

        # Download progress bar
        self.dl_pbar = ProgressBar(self, minimum=0, maximum=100, textVisible=False, objectName="RedProgressBar")
        self.dl_pbar.setMaximumWidth(165)
        self.status_bar.addPermanentWidget(self.dl_pbar)


        # STATUS BAR MESSAGES
        
        self.setStatusBar(self.status_bar)
        self.mainNotebook.tab1.performingSearch.connect(lambda: self.status_bar.showMessage('Performing search...'))
        self.mainNotebook.tab1.loadingResults.connect(lambda: self.status_bar.showMessage('Loading results...'))
        self.mainNotebook.tab1.downloadStartedB.connect(self.status_bar.showMessage)
        self.mainNotebook.tab1.downloadStartedB.connect(self.dl_pbar.startDownload)
        self.mainNotebook.tab1.downloadFinishedB.connect(self.status_bar.showMessage)
        self.mainNotebook.tab1.downloadFinishedB.connect(self.dl_pbar.finishDownload)
        self.mainNotebook.tab1.resultsLoaded.connect(self.status_bar.showMessage)
        self.mainNotebook.tab1.downloadUnzippedB.connect(self.mainNotebook.tab3.downloadList.addItem)
        self.mainNotebook.tab1.nicknameChosenB.connect(self.databoy.add_scan)
    

        

class MyNotebook(qtw.QWidget):

    def __init__(self, parent):
        super(qtw.QWidget, self).__init__(parent)
        self.layout = qtw.QVBoxLayout(self)

        # Initialize tabs
        self.tabs = qtw.QTabWidget()
        self.tab1 = QHypbrowser(self)
        self.tab2 = qProfileManager()
        self.tab3 = qViewer()
        self.tabs.resize(300,200)


        # Add tabs
        self.tabs.addTab(self.tab1, "USGS Search")
        self.tabs.addTab(self.tab2, "Profile Manager")
        self.tabs.addTab(self.tab3, "Image Viewer")


        # Add tabs to widget
        self.layout.addWidget(self.tabs)
        self.setLayout(self.layout)

   

def window():
    app = qtw.QApplication(sys.argv)
    win = MyWindow()
    
    win.show()
    sys.exit(app.exec_())

win = window()
